export const RouteEnum = Object.freeze({
  HOME: { path: '/', name: 'home' },
  ABOUT: { path: '/about', name: 'about' },
  DASHBOARD: { path: '/dashboard', name: 'dashboard' },
  SURVEY: { path: '/survey', name: 'survey' },
  LOGIN: { path: '/login', name: 'login' },
  REGISTER: { path: '/register', name: 'register' },
  ONBOARDING: { path: '/onboarding', name: 'onboarding' },
  TEAM: { path: '/teams', name: 'team'},
  SINGLE_TEAM: { path: '/team/:teamId', name: 'singleTeam'},
  NOTIFICATIONS: { path: '/notifications', name: 'notifications'},
  MESSAGES: { path: '/messages', name: 'messages'},
  REPORTS: { path: '/reports', name: 'reports'},
  SETTINGS: { path: '/settings', name: 'settings'},
  ADMIN: { path: '/admin', name: 'admin'},
  CASHBOX: { path: '/cashbox', name: 'cashbox'},
  PLAYERS: { path: '/players', name: 'players' },
  SURVEY_VERIFICATION: { path: '/survey/:surveyId/verify', name: 'surveyVerification'},
});
